import { AnalysisResult, Patient, Report } from '../types';

// NVIDIA NIM API - Free Vision Models
const BASE_URL = "/api/nvidia/v1/chat/completions";

// Internal helper to call NVIDIA API via REST
async function callGeminiAPI(payload: any) {
    // 1. Hardcoded NVIDIA Token
    const orToken = "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";

    // Convert Gemini payload to OpenAI format
    const messages = [];
    
    if (payload.systemInstruction) {
        let sysText = "";
        if (payload.systemInstruction.parts) {
            sysText = payload.systemInstruction.parts.map((p:any) => p.text).join('\n');
        }
        if (sysText) {
            messages.push({ role: 'system', content: sysText });
        }
    }

    if (payload.contents) {
        for (const content of payload.contents) {
            const role = content.role === 'model' ? 'assistant' : 'user';
            const parts = content.parts || [];
            
            const oaiContent = [];
            for (const part of parts) {
                if (part.text) {
                    oaiContent.push({ type: "text", text: part.text });
                } else if (part.inlineData) {
                    // NV API expects image_url.url
                    oaiContent.push({
                        type: "image_url",
                        image_url: {
                            url: `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`
                        }
                    });
                }
            }
            
            if (oaiContent.length === 1 && oaiContent[0].type === "text") {
                messages.push({ role, content: oaiContent[0].text });
            } else {
                messages.push({ role, content: oaiContent });
            }
        }
    }
    
    const openaiPayload = {
        model: "meta/llama-3.2-11b-vision-instruct", 
        messages: messages,
        max_tokens: 1024,
        temperature: 0.2
    };

    try {
        const response = await fetch(BASE_URL, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${orToken}`,
            },
            body: JSON.stringify(openaiPayload)
        });

        if (!response.ok) {
            const errorText = await response.text();
            console.error(`NVIDIA API Error (${response.status}):`, errorText);
            throw new Error(`API Error ${response.status}: ${errorText}`);
        }

        const data = await response.json();
        
        if (!data.choices || data.choices.length === 0) {
            throw new Error("No response generated by NVIDIA.");
        }

        return data.choices[0].message.content;

    } catch (error) {
        console.error("NVIDIA API call failed:", error);
        throw error;
    }
}

const getLanguageName = (lang: string) => {
    if (lang === 'en') return 'English';
    if (lang === 'it') return 'Italian';
    return 'Arabic';
};

const getAnalysisSchema = (language: string) => {
    const langName = getLanguageName(language);
    return {
        type: "OBJECT",
        properties: {
            risk_level: {
                type: "STRING",
                description: `Risk level for the patient case, must be one of: Low, Medium, High translated to ${langName}.`,
            },
            triage_color: {
                type: "STRING",
                description: "START Triage Protocol color classification. Must be one of: 'red' (Immediate), 'yellow' (Delayed), 'green' (Minor), 'black' (Deceased/Expectant). Based on respiration, perfusion, and mental status inferred from symptoms.",
                enum: ['red', 'yellow', 'green', 'black']
            },
            findings: {
                type: "STRING",
                description: `A concise summary of the visual findings from all images, combined with patient data, in ${langName}. Describe what you see that is medically relevant.`
            },
            red_flags: {
                type: "ARRAY",
                description: `A list of critical observations or 'red flags' that require immediate attention, in ${langName}. If none, return an empty array.`,
                items: { type: "STRING" }
            },
            medical_recommendations: {
                type: "ARRAY",
                description: `List of immediate medical actions or first-aid steps recommended for this specific case, in ${langName}. Be specific (e.g., 'Apply direct pressure', 'Elevate limb').`,
                items: { type: "STRING" }
            }
        },
        required: ['risk_level', 'triage_color', 'findings', 'red_flags', 'medical_recommendations']
    };
};


export const analyzeMedicalImage = async (
    base64Images: { data: string; mimeType: string }[],
    patientInfo: Patient,
    language: string = 'ar'
): Promise<AnalysisResult> => {

    const parts: any[] = [];
    base64Images.forEach(img => {
        parts.push({
            inlineData: { mimeType: img.mimeType, data: img.data }
        });
    });

    const langName = getLanguageName(language);
    const schema = getAnalysisSchema(language);

    const promptText = `
        Please act as a senior medical assistant AI specializing in Disaster Medicine and the START Triage Protocol.
        Analyze the attached medical image(s) and patient information very carefully and provide a highly detailed, accurate medical explanation.
        
        Patient Information:
        - Age: ${patientInfo.age}
        - General Symptoms: ${patientInfo.symptoms.join(', ')}
        - Detailed Symptoms: ${patientInfo.detailedSymptoms || 'Not provided'}
        - Additional Notes: ${patientInfo.notes || 'Not provided'}

        Your task is to provide a comprehensive, highly detailed medical assessment.
        
        Apply the START Triage Protocol Logic:
        1. **Black (Deceased/Expectant)**: No respiration or catastrophic injury incompatible with life.
        2. **Red (Immediate)**: Respiratory rate > 30, OR No radial pulse/capillary refill > 2s, OR Unable to follow commands (altered mental status).
        3. **Yellow (Delayed)**: Serious but stable. Cannot walk but respirations, pulse, and mental status are normal.
        4. **Green (Minor)**: "Walking wounded". Minor injuries.

        Your response MUST be entirely in ${langName} and formatted exactly as a valid JSON object matching this schema:
        ${JSON.stringify(schema, null, 2)}
        
        IMPORTANT RULES:
        1. Ensure ALL fields are filled out in ${langName} with detailed, highly descriptive text.
        2. DO NOT leave 'findings' or 'red_flags' empty. Be thorough and write a professional medical summary.
        3. Return ONLY the raw JSON object. Do not wrap it in a markdown block (e.g. no \`\`\`json). Just the raw JSON.
    `;

    parts.push({ text: promptText });

    try {
        const textResponse = await callGeminiAPI({
            contents: [{ parts: parts }]
        });

        let cleanText = textResponse.replace(/^[\s\S]*?```json/gm, '').replace(/```[\s\S]*?$/gm, '');
        cleanText = cleanText.trim();

        let result: any = {};
        try {
            result = JSON.parse(cleanText);
        } catch (jsonError) {
            console.error("JSON Parse Error. Raw text:", textResponse);
            const firstBrace = textResponse.indexOf('{');
            const lastBrace = textResponse.lastIndexOf('}');
            if (firstBrace !== -1 && lastBrace !== -1) {
                const subString = textResponse.substring(firstBrace, lastBrace + 1);
                result = JSON.parse(subString);
            } else {
                throw new Error("Invalid JSON structure in AI response.");
            }
        }

        // Ensure defaults so UI doesn't crash if Llama 3.2 returns incomplete JSON
        return {
            risk_level: result.risk_level || 'غير محدد',
            triage_color: result.triage_color || 'gray',
            findings: result.findings || 'لم يتمكن الذكاء الاصطناعي من توليد ملاحظات دقيقة. يرجى مراجعة الحالة يدوياً.',
            red_flags: Array.isArray(result.red_flags) ? result.red_flags : [],
            medical_recommendations: Array.isArray(result.medical_recommendations) ? result.medical_recommendations : []
        } as AnalysisResult;
    } catch (error) {
        console.error("Analysis and Parsing Failed:", error);
        throw new Error("Medical Analysis Failed. Please check your internet connection and try again.");
    }
};

export const getClinicalAssistantResponse = async (query: string, reports: Report[], language: string = 'ar'): Promise<string> => {
    const langName = getLanguageName(language);
    const reportsContext = JSON.stringify(reports.map(r => ({
        patientName: r.patientName,
        age: r.patientAge,
        symptoms: r.symptoms,
        triage: r.analysisResult.triage_color,
        analysis: r.analysisResult.findings,
    })));

    const prompt = `
        You are an "AI Medical Consultant" - a senior consulting expert backed by the latest global medical research and protocols.
        Your role is to provide formal, detailed, and highly organized medical reports for doctors and paramedics.
        
        **Available Reports Context in Hospital Database:**
        ${reportsContext}

        ---
        **User Query (Consultation requested):**
        "${query}"
        ---

        **Response Instructions (SBAR Protocol):**
        1. **Identity:** You are a "Senior Consultant in Emergency and Disaster Medicine". Analyze the field data and provide a professional summary.
        2. **SBAR Protocol:** Use the global SBAR handover protocol:
           - **Situation:** What is happening right now?
           - **Background:** Medical history and current symptoms.
           - **Assessment:** What is your conclusion based on the START Triage protocol?
           - **Recommendation:** What is the urgent next medical step?
        3. **Markdown Tables:** **Mandatory** for comparing patients or displaying vital signs.
        4. **Language:** You MUST reply entirely in ${langName}. Use precise and direct medical terminology in ${langName}.
        5. **Field-Clinical Link:** Confirm to the doctor that this data was collected in the field and help them make an immediate surgical or evacuation decision based on medical priorities.
        6. **Sources:** Rely on global quality standards (WHO, ATLS, Red Cross).
    `;

    try {
        return await callGeminiAPI({
            contents: [{ parts: [{ text: prompt }] }]
        });
    } catch (error) {
        console.error("Error getting assistant response:", error);
        return "Failed to get an answer from the assistant.";
    }
};

export const compareMedicalImages = async (oldImage: { data: string, mimeType: string }, newImage: { data: string, mimeType: string }, context: string, language: string = 'ar'): Promise<string> => {
    const langName = getLanguageName(language);
    const prompt = `
        Act as a medical expert. Compare these two images of a patient's injury.
        Image 1 is the PREVIOUS state.
        Image 2 is the CURRENT state.
        Context: ${context}
        
        Question: Is the condition improving, worsening, or stable? Describe the changes in the wound/injury (e.g., size, color, signs of infection, healing tissue).
        
        Answer ONLY and entirely in ${langName}.
    `;

    try {
        const parts = [
            { inlineData: { mimeType: oldImage.mimeType, data: oldImage.data } },
            { inlineData: { mimeType: newImage.mimeType, data: newImage.data } },
            { text: prompt }
        ];

        return await callGeminiAPI({
            contents: [{ parts: parts }]
        });
    } catch (error) {
        console.error("Error in comparative analysis:", error);
        throw new Error("Failed to compare images.");
    }
};

export const generateInventorySuggestion = async (reports: Report[], language: string = 'ar'): Promise<string> => {
    const langName = getLanguageName(language);
    const symptomsSummary = reports.map(r => r.symptoms.join(', ')).join('; ');
    const injuriesSummary = reports.map(r => r.analysisResult.findings).join('; ');

    const prompt = `
        Based on the following list of patient symptoms and injury findings from a disaster zone:
        "${symptomsSummary} | ${injuriesSummary}"

        Suggest a prioritized list of medical supplies and inventory needed to treat these specific cases (e.g., if many burns, suggest burn ointment and gauze).
        Format the response as a clear, bulleted list in ${langName}.
        Ensure everything is translated to ${langName}.
     `;

    try {
        return await callGeminiAPI({
            contents: [{ parts: [{ text: prompt }] }]
        });
    } catch (error) {
        console.error("Error generating inventory:", error);
        return "Failed to generate inventory list.";
    }
};

export const translateText = async (text: string, targetLanguage: string = 'Arabic'): Promise<string> => {
    const prompt = `Translate the following text to ${targetLanguage}. If it is already in that language, translate it to English. Only provide the translation. Text: "${text}"`;
    try {
        return await callGeminiAPI({
            contents: [{ parts: [{ text: prompt }] }]
        });
    } catch (error) {
        return "تعذر الترجمة.";
    }
}

export const sendChatResponse = async (messages: { role: 'user' | 'assistant' | 'system', content: string, attachments?: { data: string, mimeType: string }[] }[]): Promise<string> => {
    try {
        const systemMessage = messages.find(m => m.role === 'system');
        const chatHistory = messages.filter(m => m.role !== 'system').map(m => {
            const parts: any[] = [{ text: m.content }];

            if (m.attachments) {
                m.attachments.forEach(att => {
                    parts.push({
                        inlineData: {
                            mimeType: att.mimeType,
                            data: att.data
                        }
                    });
                });
            }

            return {
                role: m.role === 'user' ? 'user' : 'model',
                parts: parts
            };
        });

        const payload: any = {
            contents: chatHistory
        };

        if (systemMessage) {
            payload.system_instruction = {
                parts: [{ text: systemMessage.content }]
            };
        }

        return await callGeminiAPI(payload);
    } catch (error) {
        console.error("Error sending chat message:", error);
        throw new Error("Failed to get chat response.");
    }
};

